version: "3"

services:
  hadoop-base:
    build: base
    image: base
    container_name: hadoop-base
    deploy:
      replicas: 1

  namenode:
    build: namenode
    image: namenode
    depends_on:
      - hadoop-base
    container_name: namenode
    restart: always
    networks:
      - cluster
    ports:
      - 9870:9870
      - 9000:9000
      - 9999:8888
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      # TODO: Voeg hier extra folders toe om ze zichtbaar te maken in je containers, deze hebben de volgende structuur:
      # {local absolute path}:/home/bigdata/{folderstructuur waar je ze wil hebben}
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    build: datanode
    image: datanode
    depends_on:
      - namenode
    container_name: datanode
    restart: always
    networks:
      - cluster
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    build: resourcemanager
    image: resourcemanager
    depends_on:
      - namenode
    container_name: resourcemanager
    restart: always
    networks:
      - cluster
    ports:
      - 8032:8032
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    depends_on:
      - namenode
    build: nodemanager
    image: nodemanager
    networks:
      - cluster
    ports:
      - 8042:8042
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    build: historyserver
    image: historyserver
    depends_on:
      - namenode
    container_name: historyserver
    restart: always
    networks:
      - cluster
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - cluster
    ports:
     - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
